genome_folder: ../Strainify_paper/simulated_exp/30_strain_simulated/ecoli/ecoli_downloads
output_dir: ../Strainify_paper/simulated_exp/strainify/30_strain_simulated/ecoli/not_weighted
fastq_folder: ../Strainify_paper/simulated_exp/30_strain_simulated/ecoli/fastq
read_type: paired
modify_windows: --window_size 500 --window_overlap 0
weight_by_entropy: false
use_precomputed_variants: false