genome_folder: ../Strainify_paper/4_strain_mock_community/genomes
output_dir: ../Strainify_paper/4_strain_mock_community/strainify/results
fastq_folder: ../Strainify_paper/4_strain_mock_community/fastq
read_type: paired
modify_windows: --window_size 500 --window_overlap 0
weight_by_entropy: false
use_precomputed_variants: false